### ISSUE TITLE
favicon 196

### ISSUE THREAD

**Issue by fuen0015** [fuen0015/responsive-recipe-book#1]
Hello Thomas,
Markbot is requesting that we need favicon-196, I did a png in illustrator to those dimensions but the software for favicons does not offer this size. What do I do?
<img width="501" alt="Screen Shot 2020-01-16 at 11 18 08 AM" src="https://user-images.githubusercontent.com/43240727/72542293-e85ae980-3851-11ea-9e52-92dc53a7c6e4.png">

@thomasjbradley

**Comment by thomasjbradley** [comment]
It’s supposed to be left as a PNG, named `favicon-196.png`

**Comment by fuen0015** [comment]
so I should just compress it and leave it? but what about the favicon.ico I can't retrieve that

**Comment by thomasjbradley** [comment]
Follow the steps here:
https://learn-the-web.algonquindesign.ca/courses/web-dev-3/micro-interface-branding/

**Comment by fuen0015** [comment]
I have done the steps but it is still showing me this message and my favicon worked, what is causing it?
<img width="499" alt="Screen Shot 2020-01-16 at 11 49 05 AM" src="https://user-images.githubusercontent.com/43240727/72544971-438edb00-3856-11ea-9dd7-c9fc6da780a8.png">

**Comment by thomasjbradley** [comment]
You have the favicon HTML tags on `recipes.html` but not in `index.html`

**Comment by fuen0015** [comment]
They are on both but still getting this
<img width="510" alt="Screen Shot 2020-01-16 at 11 53 29 AM" src="https://user-images.githubusercontent.com/43240727/72545355-e6475980-3856-11ea-939f-c8726a48c6f2.png">

**Comment by thomasjbradley** [comment]
They shouldn’t be in the `images` folder, they should be out in the root folder.

**Comment by fuen0015** [comment]
That was it! Thank you :)
